import Config

# Configure your database
dev_db_username =
  System.get_env("DEV_DATABASE_USERNAME") || System.get_env("DATABASE_USERNAME") || "postgres"

dev_db_password =
  System.get_env("DEV_DATABASE_PASSWORD") || System.get_env("DATABASE_PASSWORD") || "postgres"

dev_db_host =
  System.get_env("DEV_DATABASE_HOST") || System.get_env("DATABASE_HOST") || "localhost"

dev_db_port =
  System.get_env("DEV_DATABASE_PORT") || System.get_env("DATABASE_PORT") || "5432"

config :money_tree, MoneyTree.Repo,
  username: dev_db_username,
  password: dev_db_password,
  hostname: dev_db_host,
  port: String.to_integer(dev_db_port),
  database: System.get_env("DEV_DATABASE_NAME") || "money_tree_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("DEV_DATABASE_POOL_SIZE") || "10")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :money_tree, MoneyTreeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "phyLbEeTQE24hcZMhVv+OA9FlwwH3+wnDnQIOffpLMPHzaOjtxVT6Sa4OaVdpRwJ",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :money_tree, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Run Oban locally without peer discovery in development and use lighter queue limits.
config :money_tree, Oban,
  peer: false,
  queues: [default: 5, mailers: 2, reporting: 1]
