name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  MIX_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: Determine pnpm store path
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install workspace dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16.2"
          otp-version: "26.2.2"

      - name: Cache deps and build artifacts
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            apps/money_tree/priv/plts
            ~/.mix
            ~/.hex
          key: ${{ runner.os }}-mix-${{ env.MIX_ENV }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.MIX_ENV }}-
            ${{ runner.os }}-mix-

      - name: Install Hex/Rebar
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install dependencies
        run: mix deps.get

      - name: Compile (warnings as errors)
        run: mix compile --warnings-as-errors

      - name: Format check
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --strict

      - name: Tests
        run: mix test
        timeout-minutes: 15

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
        timeout-minutes: 25

      - name: Build shared UI styles
        run: pnpm --filter ui build

      - name: Cache Next.js build artifacts
        uses: actions/cache@v3
        with:
          path: |
            apps/next/.next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('pnpm-lock.yaml', 'apps/next/package.json', 'apps/next/next.config.*', 'apps/next/tailwind.config.*', 'apps/next/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-next-

      - name: Next.js lint
        run: pnpm --filter next lint

      - name: Next.js tests
        run: pnpm --filter next test

      - name: Build Next.js app
        run: pnpm --filter next build

      - name: Next.js audit
        run: pnpm audit --dir apps/next

      - name: Build Phoenix assets
        run: pnpm --filter money-tree-assets build

      - name: Verify API contracts
        run: pnpm --filter @moneytree/contracts... run verify
