name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  MIX_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/money_tree

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16.2"
          otp-version: "26.2.2"

      - name: Cache deps and build artifacts
        uses: actions/cache@v3
        with:
          path: |
            apps/money_tree/deps
            apps/money_tree/_build
            apps/money_tree/priv/plts
            ~/.mix
            ~/.hex
          key: ${{ runner.os }}-mix-${{ env.MIX_ENV }}-${{ hashFiles('apps/money_tree/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.MIX_ENV }}-
            ${{ runner.os }}-mix-

      - name: Install Hex/Rebar
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install dependencies
        run: mix deps.get

      - name: Compile (warnings as errors)
        run: mix compile --warnings-as-errors

      - name: Format check
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --strict

      - name: Tests
        run: mix test

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
